name: Build and Release HLTB for Deck

on:
    push:
        tags:
            - 'v*'
    pull_request:
        branches: ['main']

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '18.3'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install Dependencies
              run: pnpm install

            - name: build
              run: pnpm run build

            - name: copy files into build
              run: |
                  cp plugin.json ./dist/
                  cp package.json ./dist/
                  mkdir ./dist/dist
                  mv ./dist/index.js ./dist/dist/

            - name: Upload package
              uses: actions/upload-artifact@v4
              with:
                  name: hltb-for-deck
                  path: |
                      ./dist/*
    release:
        needs: build
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/download-artifact@v4
              with:
                  name: hltb-for-deck
                  path: hltb-for-deck

            - name: zip/tar release
              run: |
                  zip -r hltb-for-deck.zip hltb-for-deck/*
                  tar -czvf hltb-for-deck.tar.gz hltb-for-deck

            - name: Create a release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: 'hltb-for-deck.zip,hltb-for-deck.tar.gz'
                  bodyFile: 'release.md'
                  token: ${{ secrets.GITHUB_TOKEN }}
